name: Android AAB Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build and Sign Production AAB
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Decode keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > production.keystore
          echo "KEYSTORE_PATH=$PWD/production.keystore" >> $GITHUB_ENV

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      - name: Build Production Release AAB
        run: ./gradlew bundleProductionRelease
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          KEYSTORE_PATH: ${{ env.KEYSTORE_PATH }}

      - name: Upload Production AAB
        uses: actions/upload-artifact@v4
        with:
          name: production-release-aab
          path: presentation/build/outputs/bundle/productionRelease/presentation-production-release.aab
